import {
  AlignLeft,
  Hash,
  Calendar,
  CheckSquare,
  Tag,
  Tags,
  Link2,
  Mail,
  Phone,
  User,
  Paperclip,
  GitBranch,
  FunctionSquare,
  Sigma,
  Clock,
  MapPin,
  CircleDot,
  type LucideIcon,
} from "lucide-react";
import type { PropertyValueType } from "@/lib/types/properties";

export const PROPERTY_TYPE_ICONS: Record<PropertyValueType, LucideIcon> = {
  text: AlignLeft,
  number: Hash,
  date: Calendar,
  boolean: CheckSquare,
  select: Tag,
  multi_select: Tags,
  status: CircleDot,
  url: Link2,
  email: Mail,
  phone: Phone,
  person: User,
  file: Paperclip,
  relation: GitBranch,
  formula: FunctionSquare,
  rollup: Sigma,
  checkbox: CheckSquare,
  created_time: Clock,
  last_edited_time: Clock,
  created_by: User,
  last_edited_by: User,
  location: MapPin,
};

export const PROPERTY_TYPE_LABELS: Record<PropertyValueType, string> = {
  text: "Text",
  number: "Number",
  date: "Date",
  boolean: "Boolean",
  select: "Select",
  multi_select: "Multi-select",
  status: "Status",
  url: "URL",
  email: "Email",
  phone: "Phone",
  person: "Person",
  file: "Files & media",
  relation: "Relation",
  formula: "Formula",
  rollup: "Rollup",
  checkbox: "Checkbox",
  created_time: "Created time",
  last_edited_time: "Last edited time",
  created_by: "Created by",
  last_edited_by: "Last edited by",
  location: "Location",
};
